version: '3.5'

services:
    customer_analysis:
        container_name: customer_analysis
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/src/
        ports:
            - 8877:8877
        restart: always

